### ISSUE TITLE
Android 10 and LineageOS 17.1 support

### ISSUE THREAD

**Issue by Pl0414141** [lineage-rpi/android_kernel_brcm_rpi#1]
Hi,

Are you planning to update the repository to support Android 10 and LineageOS 17.1?

I would be very grateful, thank you very much.

**Comment by KonstaT** [comment]
Kernel built from this repository would already boot LineageOS 17.1/Android 10 just fine. This is actually Android 10 (Q) kernel with some backports to make it work with Android Pie.

I haven't released the complete device specific source code for LineageOS 16.0 builds either. This is because someone sold builds off of the sources I previously released without complying with the open source licensing.
