### ISSUE TITLE
Accessing Peripherals from Android SDK?

### ISSUE THREAD

**Issue by jerradpatch** [lineage-rpi/android_kernel_brcm_rpi#13]
**Describe the bug**

I feel this must be a simple issue, however I am not a linux/android OS developer. I was wondering how to access the deivice hardware, specifically the SPI port. I see that there is a SPI port provided but the method provided for the Android of Things (PeripheralManager) does not exist on the device (shared libraries). I am referencing these docs on the manager, https://developer.android.com/things/training/first-device/peripherals. Any information would be great or some docs, thanks again.

**Expected behaviour**
Add a clear and concise description of what you expected to happen.

val manager = PeripheralManager.getInstance();

is expected to return the manager, instead an exception is thrown.

**Actual behaviour**
Add a clear and concise description of what actually happened.

an exception is thrown saying it cant find the library.

**Comment by KonstaT** [comment]
Android != Android Things. I haven't released any Android Things builds and it wouldn't even be possible because Android Things is not open source. There's no access to Android Things APIs in regular Android builds.

Google has made Android Things developer preview images available for Raspberry Pi 3 model B but for newer models (i.e. even Pi 3B+). I think they announced discontinuing Android Things a while back so I'd suggest downloading the final images while you still can.
