### ISSUE TITLE
Waveshare xinch DSI touchscreen recovery support

### ISSUE THREAD

**Issue by belliash** [lineage-rpi/android_kernel_brcm_rpi#33]
### Describe the bug

In #32 you have added support for Waveshare DSI touchscreen. It is working fine and even booting into recovery enables the display after kernel upgrade (I mean screen is on). However nothing shows on the screen.

Do you know what is missing and if this can be easily fixed (i.e. in next release)?

### Steps to reproduce the behaviour

Boot into recovery.

### Device (s)

Raspberry Pi 4 Mod. B

### System

LineageOS 20.0-20230505-UNOFFICIAL-KonstaKANG-rpi4 with AOSP13-20230426-KonstaKANG-rpi4-6.1-kernel.zip

**Comment by KonstaT** [comment]
TWRP doesn't use hw accelerated graphics (i.e. `dtoverlay=vc4-kms-v3d` is commented out when booting to recovery). So, you would need to comment out/remove the `dtoverlay=vc4-kms-dsi-waveshare-panel,...` line as well when booting to TWRP. You would also need to uncomment `dtoverlay=goodix` to enable the touchscreen driver that would get enabled with 'vc4-kms-dsi-waveshare-panel' overlay otherwise.

There's no plans for any release with Linux 6.1 kernel (and Waveshare DSI touchscreen support) until Android 14. Even then it's unlikely I'll add any settings option/etc for these display panels so these need to configured separately in any case.

Closing as this discussion could have just as well continued at https://github.com/lineage-rpi/android_kernel_brcm_rpi/issues/32.
