### ISSUE TITLE
Any docmuments for rebuilding your built LineageOS 17.1 image?

### ISSUE THREAD

**Issue by tonyho** [lineage-rpi/android_kernel_brcm_rpi#7]
It's wonderful to find "LineageOS 17.1 (Android 10) for Raspberry Pi 4", and I want to use the raspberryPi4 as the Android 10 target development board,  so if there is any documents about how to rebuild the the LineageOS 17.1 (Android 10)  image for raspberryPi4?   

Something like: 
```
repo init XXXX, 
repo sync
make XXX
```

Thanks.

**Comment by KonstaT** [comment]
There's source code and build instructions for my LineageOS 14.1 & 15.1 builds for Pi 3 (https://github.com/lineage-rpi/android_local_manifest/tree/cm-14.1 & https://github.com/lineage-rpi/android_local_manifest/tree/lineage-15.1, respectively). I haven't released the full device specific source code for my LineageOS 16.0 & 17.1 builds (both Pi 3 & Pi 4) because someone sold builds off of the sources I previously released without complying with open source licensing.
