### ISSUE TITLE
Can integrate ssh and vnc

### ISSUE THREAD

**Issue by tab-1** [lineage-rpi/android_kernel_brcm_rpi#9]
I want to use ssh and vnc on Android. Does this ROM support? In addition, I found that I am building lineage17 on rpi4B, it will restart after unplugging the screen

**Comment by KonstaT** [comment]
My LineageOS 17.1 builds already have a built-in SSH server. It requires some steps to use it because it uses key based authentication. If/when there is another release, there will be a settings option to start/stop the SSH server.

I've been told various VNC apps work so why would it need to be integrated into the build?

Graphics drivers used for hw accelerated graphics in this build rely on the EDID information your connected HDMI display sends. Please read the FAQ what you need to do if you want to run without any display connected.

**Comment by tab-1** [comment]
I want to run without any display connected, but I didn't find the FAQ you mentioned, can you write me instructions?

**Comment by KonstaT** [comment]
https://konstakang.com/devices/rpi4/LineageOS17.1/

If you want to run headless one option is to buy a dummy HDMI plug if you don't want to have an actual display connected.
